"""Trusted contained Git checkout materializer for DevForge workspaces (D5).

The materializer never clones, never fetches, never invokes network Git and
never reads credentials.  It receives one provider-sealed source capsule plus
the exact workspace binding and writes a minimal normal Git repository that
satisfies the exact readback contract:

    git rev-parse --show-toplevel == exact workspace
    git rev-parse HEAD            == expected_commit
    git branch --show-current     == admitted logical branch
    git remote get-url origin     == admitted repository identity
    git status --porcelain        == clean

The provider worker source is generated by ``build_materializer_worker()`` as
a self-contained stdlib-only script so it can run inside the AppContainer
without importing the host package.  ``materialize_from_capsule()`` compiles
the same single source of truth in-process for direct testing.
"""
from __future__ import annotations

import json
from pathlib import Path

MATERIALIZER_SCRIPT_NAME = "__devforge_materializer__.py"
MATERIALIZER_RESULT_NAME = "__devforge_materializer_result__.json"

_WORKER_SOURCE = '''
"""Self-contained trusted materializer worker (provider-generated)."""
from __future__ import annotations

import hashlib
import json
import os
import stat
import sys
import zlib
from pathlib import Path, PurePosixPath

RESULT_NAME = "__devforge_materializer_result__.json"
ALLOWED_MODES = frozenset({"100644", "100755"})


def _fail(result: dict, message: str) -> None:
    result["ok"] = False
    result["error"] = message
    sys.stderr.write(message + "\\n")
    raise SystemExit(_emit(result, 1))


def _emit(result: dict, code: int) -> int:
    payload = json.dumps(result, sort_keys=True, separators=(",", ":"))
    (Path.cwd() / RESULT_NAME).write_text(payload, encoding="utf-8", newline="\\n")
    return code


def _verify_inside(workspace: Path, target: Path) -> Path:
    resolved = target.resolve(strict=False)
    root = workspace.resolve(strict=False)
    if resolved != root and not resolved.is_relative_to(root):
        _fail({}, "materializer write escaped the exact workspace")
    return resolved


def _safe_entry_path(raw: str) -> PurePosixPath:
    pure = PurePosixPath(raw)
    if pure.is_absolute() or raw.startswith("/") or ":" in raw or "\\\\" in raw:
        raise ValueError("absolute capsule entry path")
    if any(part in ("", ".", "..") for part in pure.parts):
        raise ValueError("unsafe capsule entry path")
    return pure


def _read_manifest(capsule: Path) -> dict:
    metadata_path = capsule / "manifest.json"
    manifest = json.loads(metadata_path.read_text(encoding="utf-8"))
    body = {key: value for key, value in manifest.items() if key != "manifest_digest"}
    canonical = json.dumps(body, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    if digest != manifest.get("manifest_digest"):
        raise ValueError("capsule manifest digest mismatch")
    return manifest


def materialize_from_capsule(capsule: Path, workspace: Path) -> dict:
    result: dict = {"ok": False, "manifest_digest": None}
    manifest = _read_manifest(capsule)
    result["manifest_digest"] = manifest.get("manifest_digest")
    result["expected_commit"] = manifest.get("expected_commit")

    logical = manifest["logical_branch"]
    if not logical or logical.startswith("/") or ".." in logical:
        _fail(result, "unsafe logical branch name")

    own_script = Path(sys.argv[0]).resolve(strict=False) if sys.argv and sys.argv[0] else None
    existing = sorted(
        entry
        for entry in workspace.iterdir()
        if not (own_script is not None and entry.resolve(strict=False) == own_script)
    )
    if existing:
        _fail(result, "exact workspace is not empty before materialization")

    objects: dict[str, tuple[str, bytes]] = {}
    for sha in manifest["objects"]:
        object_path = capsule / "objects" / sha[:2] / sha[2:]
        raw = object_path.read_bytes()
        inflated = zlib.decompress(raw)
        header, _, payload = inflated.partition(b"\\x00")
        obj_type, _, size_text = header.decode("ascii").partition(" ")
        if int(size_text) != len(payload) or hashlib.sha1(inflated).hexdigest() != sha:
            _fail(result, f"capsule object {sha} failed content verification")
        objects[sha] = (obj_type, payload)

    git_dir = _verify_inside(workspace, workspace / ".git")
    if git_dir.exists():
        _fail(result, "exact workspace already contains Git metadata")
    git_dir.mkdir(parents=True)
    (git_dir / "objects").mkdir()
    (git_dir / "refs" / "heads").mkdir(parents=True)

    total_bytes = 0
    file_count = 0
    for entry in manifest["entries"]:
        pure = _safe_entry_path(entry["path"])
        if entry["mode"] not in ALLOWED_MODES:
            _fail(result, f"unsupported file mode for {entry['path']}")
        sha = entry["sha"]
        if sha not in objects:
            _fail(result, f"capsule is missing object {sha}")
        obj_type, payload = objects[sha]
        if obj_type != "blob" or len(payload) != int(entry["size"]):
            _fail(result, f"blob payload mismatch for {entry['path']}")
        target = _verify_inside(workspace, workspace.joinpath(*pure.parts))
        if target.exists():
            _fail(result, f"capsule contains duplicate path {entry['path']}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)
        os.chmod(target, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
        total_bytes += len(payload)
        file_count += 1

    for sha in manifest["objects"]:
        obj_type, payload = objects[sha]
        header = f"{obj_type} {len(payload)}\\x00".encode("ascii")
        inflated = header + payload
        if hashlib.sha1(inflated).hexdigest() != sha:
            _fail(result, f"object {sha} hash mismatch during metadata write")
        loose_dir = _verify_inside(workspace, git_dir / "objects" / sha[:2])
        loose_dir.mkdir(parents=True, exist_ok=True)
        (loose_dir / sha[2:]).write_bytes(zlib.compress(inflated))

    (git_dir / "HEAD").write_text(f"ref: refs/heads/{logical}\\n", encoding="ascii")
    (git_dir / "refs" / "heads" / logical).parent.mkdir(parents=True, exist_ok=True)
    (git_dir / "refs" / "heads" / logical).write_text(
        manifest["expected_commit"] + "\\n", encoding="ascii"
    )
    origin_url = manifest["origin_url"]
    config = (
        "[core]\\n"
        "\\trepositoryformatversion = 0\\n"
        "\\tfilemode = false\\n"
        "\\tbare = false\\n"
        "\\tlogallrefupdates = true\\n"
        "[remote \\"origin\\"]\\n"
        f"\\turl = {origin_url}\\n"
        "\\tfetch = +refs/heads/*:refs/remotes/origin/*\\n"
        f"[branch \\"{logical}\\"]\\n"
        "\\tremote = origin\\n"
        f"\\tmerge = refs/heads/{logical}\\n"
    )
    (git_dir / "config").write_text(config, encoding="utf-8", newline="\\n")

    if own_script is not None and own_script.is_relative_to(workspace.resolve(strict=False)):
        try:
            own_script.unlink()
        except OSError:
            pass

    result["ok"] = True
    result["file_count"] = file_count
    result["total_bytes"] = total_bytes
    _emit(result, 0)
    sys.stdout.write(json.dumps(result, sort_keys=True, separators=(",", ":")) + "\\n")
    return result


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        sys.stderr.write("usage: materializer <capsule-dir>\\n")
        return 2
    result: dict = {"ok": False}
    try:
        capsule = Path(argv[1]).resolve(strict=True)
        workspace = Path.cwd().resolve(strict=True)
        materialize_from_capsule(capsule, workspace)
        return 0
    except SystemExit:
        raise
    except Exception as exc:  # noqa: BLE001
        result["error"] = f"{type(exc).__name__}: {exc}"
        try:
            sys.stderr.write(result["error"] + "\\n")
            (Path.cwd() / RESULT_NAME).write_text(
                json.dumps(result, sort_keys=True, separators=(",", ":")),
                encoding="utf-8",
                newline="\\n",
            )
        except OSError:
            pass
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
'''


class MaterializerError(RuntimeError):
    code = "WorkspaceMaterializerFailed"


def build_materializer_worker() -> bytes:
    """Return the exact provider-generated worker bytes (sealed as evidence)."""
    return _WORKER_SOURCE.encode("utf-8")


def _worker_namespace() -> dict:
    namespace: dict[str, object] = {"__name__": "devforge_materializer_worker"}
    exec(compile(_WORKER_SOURCE, MATERIALIZER_SCRIPT_NAME, "exec"), namespace)  # noqa: S102
    return namespace


def materialize_from_capsule(capsule: Path, workspace: Path) -> dict:
    """Run the exact worker logic in-process (tests and broker-side verification).

    The worker signals failure with ``SystemExit`` (process mode) or plain
    ``ValueError``/``OSError`` (validation); both map onto the stable
    ``MaterializerError`` surface for broker callers.
    """
    namespace = _worker_namespace()
    try:
        return namespace["materialize_from_capsule"](Path(capsule), Path(workspace))  # type: ignore[no-any-return]
    except SystemExit as exc:
        raise MaterializerError(
            f"materializer worker failed with exit code {exc.code}"
        ) from exc
    except (ValueError, OSError) as exc:
        raise MaterializerError(f"materializer worker failed: {exc}") from exc


def parse_worker_result(payload: bytes) -> dict:
    try:
        result = json.loads(payload.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise MaterializerError(f"materializer result is not valid JSON: {exc}") from exc
    if not isinstance(result, dict) or result.get("ok") is not True:
        raise MaterializerError(f"materializer failed: {result.get('error', 'unknown error')}")
    return result
